import loginPage from "../../support/project akhir"
import loginData from "../../fixtures/data project akhir.json"

describe('Project akhir', () => {
    it('TC-001: Login Berhasil dengan Username dan Password Valid', () => {
    loginPage.visitlogin()
    loginPage.inputUsername(loginData.validUsername)
    loginPage.inputPassword(loginData.validPassword)
    loginPage.interceptDashboard()
    loginPage.loginButton()
    loginPage.waitForDashboard()
    loginPage.assertionLogin()
 })
    it('TC-002: Login gagal dengan Password invalid', () => {
    loginPage.visitlogin()
    loginPage.inputUsername(loginData.validUsername)
    loginPage.inputPassword(loginData.invalidPassword)
    loginPage.interceptValidate()
    loginPage.loginButton()
    loginPage.waitForValidate()
    loginPage.invalidCredentials()
 })
    it('TC-003: Login gagal dengan Username invalid', () => {
    loginPage.visitlogin()
    loginPage.inputUsername(loginData.invalidUsername)
    loginPage.inputPassword(loginData.validPassword)
    loginPage.interceptValidate()
    loginPage.loginButton()
    loginPage.waitForValidate()    
    loginPage.invalidCredentials()
 })
    it('TC-004: Login gagal dengan field kosong', () => {
    loginPage.visitlogin()
    loginPage.loginButton()
    loginPage.requiredLogin()
 })
    it('TC-005: Verifikasi Tautan Forgot Password', () => {
    loginPage.visitlogin()
    loginPage.interceptResetPassword()
    loginPage.forgotPassword()
    loginPage.waitForResetPassword()
 })
    it('TC-006: Cancel Verifikasi Tautan Forgot Password', () => {
    loginPage.visitlogin()
    loginPage.forgotPassword()
    loginPage.interceptCancelResetPassword()
    loginPage.cancelResetPassword()
    loginPage.waitForCancelResetPassword()
 }) 
    it('TC-007: View Submenu Directory', () => {
    loginPage.visitlogin()
    loginPage.inputUsername(loginData.validUsername)
    loginPage.inputPassword(loginData.validPassword)
    loginPage.loginButton()
    loginPage.intercpetDirectory()
    loginPage.menuDirectory()
    loginPage.waitForDirectory()
    loginPage.assertionDirectory()
 }) 
 it('TC-008: Test Filter Search Name Menu Directory', () => {
    loginPage.visitlogin()
    loginPage.inputUsername(loginData.validUsername)
    loginPage.inputPassword(loginData.validPassword)
    loginPage.loginButton()
    loginPage.menuDirectory()
    loginPage.assertionDirectory()
    loginPage.inputSearchNameDirectory(loginData.employeeName)
    loginPage.interceptSearchDirectory()
    loginPage.clickSearch()
    loginPage.waitForSearchDirectory() 
 }) 
    it('TC-009: Test Filter Dropdown Job Title Menu Directory', () => {
    loginPage.visitlogin()
    loginPage.inputUsername(loginData.validUsername)
    loginPage.inputPassword(loginData.validPassword)
    loginPage.loginButton()
    loginPage.menuDirectory()
    loginPage.assertionDirectory()
    loginPage.selectJobTitleDirectory(loginData.jobTitle)
    loginPage.interceptSearchDirectory()
    loginPage.clickSearch()
    loginPage.waitForSearchDirectory()
 })
    it('TC-010: Test Filter Dropdown Location Menu Directory', () => {
    loginPage.visitlogin()
    loginPage.inputUsername(loginData.validUsername)
    loginPage.inputPassword(loginData.validPassword)
    loginPage.loginButton()
    loginPage.menuDirectory()
    loginPage.assertionDirectory()
    loginPage.selectLocation(loginData.location)
    loginPage.interceptSearchDirectory()
    loginPage.clickSearch()
    loginPage.waitForSearchDirectory() 
 })
	it('TC-011: Test Reset Filter', () => {
    loginPage.visitlogin()
    loginPage.inputUsername(loginData.validUsername)
    loginPage.inputPassword(loginData.validPassword)
    loginPage.loginButton()
    loginPage.menuDirectory()
    loginPage.assertionDirectory()
    loginPage.inputSearchNameDirectory(loginData.employeeName)
    loginPage.selectJobTitleDirectory(loginData.jobTitle)
    loginPage.selectLocation(loginData.location)
    loginPage.clickSearch()
    loginPage.interceptResetSearchDirectory()
    loginPage.clickResetSearch()
    loginPage.waitForResetSearchDirectory() 
 })
	it('TC-012: View Detail Employee', () => {
    loginPage.visitlogin()
    loginPage.inputUsername(loginData.validUsername)
    loginPage.inputPassword(loginData.validPassword)
    loginPage.loginButton()
    loginPage.menuDirectory()
    loginPage.assertionDirectory()
    loginPage.viewDetailEmployee(loginData.detailEmployee)
 })
    it('TC-013: Klik Back from View Detail Employee', () => {
    loginPage.visitlogin()
    loginPage.inputUsername(loginData.validUsername)
    loginPage.inputPassword(loginData.validPassword)
    loginPage.loginButton()
    loginPage.menuDirectory()
    loginPage.assertionDirectory()
    loginPage.viewDetailEmployee(loginData.detailEmployee)
    loginPage.backFromViewDetailEmployee()
 })
    it('TC-014: Copy Work Telephone from View Detail Employee', () => {
    loginPage.visitlogin()
    loginPage.inputUsername(loginData.validUsername)
    loginPage.inputPassword(loginData.validPassword)
    loginPage.loginButton()
    loginPage.menuDirectory()
    loginPage.assertionDirectory()
    loginPage.viewDetailEmployee(loginData.detailEmployee)
    loginPage.copyWorkTelephoneFromViewDetailEmployee()
 })
})